import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),assetDir=path.join(root,'docs/assets/reference-site'),provDir=path.join(root,'.github/reference-site/provenance');
const pp=process.env.TC_PUPPETEER_MODULE,puppeteer=(await import(pp?pathToFileURL(path.resolve(pp)).href:'puppeteer')).default;const chrome=process.env.TC_CHROME;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),data=p=>'data:image/png;base64,'+fs.readFileSync(p).toString('base64');
const placements=JSON.parse(fs.readFileSync(path.join(provDir,'screen-placement.json'),'utf8')).specs;
const captures=Object.fromEntries(JSON.parse(fs.readFileSync(path.join(provDir,'product-captures.json'),'utf8')).captures.map(x=>[x.id,x]));
const config={
 room:{capture:'charts',output:'room-screen.webp',css:[1024,442],viewport:[2048,884],planeScale:2,outputScale:2},
 laptop:{capture:'models',output:'laptop-screen.webp',css:[1024,314],viewport:[2048,628],planeScale:2,outputScale:2}
};
function matrix(H,inputScale,outputScale){const [[a,b,c],[d,e,f],[g,h,i]]=H;return [outputScale*a/inputScale,outputScale*d/inputScale,0,g/inputScale,outputScale*b/inputScale,outputScale*e/inputScale,0,h/inputScale,0,0,1,0,outputScale*c,outputScale*f,0,i].map(x=>Number(x).toPrecision(17)).join(',');}
async function bounds(browser,buf){const p=await browser.newPage();const value=await p.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const g=c.getContext('2d');g.drawImage(img,0,0);const d=g.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1,count=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){if(d[(y*c.width+x)*4+3]>8){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++;}}return [minX,minY,maxX,maxY,count];},'data:image/webp;base64,'+buf.toString('base64'));await p.close();return value;}
let browser;const layers=[];
try{browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--allow-file-access-from-files','--disable-dev-shm-usage']});
 for(const [scene,cfg] of Object.entries(config)){const placement=placements.find(x=>x.scene===scene),capture=captures[cfg.capture];if(!placement||!capture)throw new Error('Missing provenance '+scene);
  const sourcePath=path.join(assetDir,'original-'+cfg.capture+'.png'),source=fs.readFileSync(sourcePath);if(sha(source)!==capture.original_sha256)throw new Error('Original capture hash mismatch '+scene);
  const s=cfg.planeScale,pw=placement.plane[0]*s,ph=placement.plane[1]*s;
  let content='';
  if(scene==='room'){const [x0,y0,x1,y1]=placement.crop,[previewW,previewH]=capture.asset_dimensions,[origW,origH]=capture.original_dimensions;const targetW=placement.letterbox_dimensions[0]*s,targetH=placement.letterbox_dimensions[1]*s;const scaledH=origH*(targetW/origW),top=(y0/previewH)*scaledH;content=`<div class="content" style="left:0px;top:${placement.letterbox_offset[1]*s}px;width:${targetW}px;height:${targetH}px"><img src="${data(sourcePath)}" style="width:${targetW}px;height:auto;left:0;top:-${top}px"></div>`;}
  else{const targetW=placement.letterbox_dimensions[0]*s,targetH=placement.letterbox_dimensions[1]*s;content=`<div class="content" style="left:${placement.letterbox_offset[0]*s}px;top:0;width:${targetW}px;height:${targetH}px"><img src="${data(sourcePath)}" style="width:100%;height:100%;object-fit:contain;left:0;top:0"></div>`;}
  const html=`<!doctype html><style>html,body{margin:0;width:100%;height:100%;background:transparent;overflow:hidden}.plane{position:absolute;left:0;top:0;width:${pw}px;height:${ph}px;overflow:hidden;background:#06090c;transform-origin:0 0;transform:matrix3d(${matrix(placement.plane_to_scene_matrix,s,cfg.outputScale)})}.content{position:absolute;overflow:hidden;background:#06090c}.content img{position:absolute;display:block}</style><div class="plane">${content}</div>`;
  const p=await browser.newPage();await p.setViewport({width:cfg.viewport[0],height:cfg.viewport[1],deviceScaleFactor:1});await p.setContent(html,{waitUntil:'load'});await p.waitForFunction(()=>[...document.images].every(x=>x.complete&&x.naturalWidth));const output=await p.screenshot({type:'webp',quality:96,omitBackground:true});await p.close();fs.writeFileSync(path.join(assetDir,cfg.output),output);
  const ab=await bounds(browser,output);layers.push({scene,capture:cfg.capture,source_asset:'docs/assets/reference-site/original-'+cfg.capture+'.png',source_sha256:capture.original_sha256,source_dimensions:capture.original_dimensions,placement_source:'.github/reference-site/provenance/screen-placement.json',plane_scale:s,output_asset:'docs/assets/reference-site/'+cfg.output,css_dimensions:cfg.css,output_dimensions:cfg.viewport,output_scale:cfg.outputScale,output_sha256:sha(output),alpha_bounds:ab.slice(0,4),nontransparent_pixels:ab[4],generator:'.github/scripts/generate_reference_screen_layers.mjs',data_classification:capture.data_classification,release_approved:false});}
}finally{if(browser)await browser.close();}
const generatorRel='.github/scripts/generate_reference_screen_layers.mjs',generatorPath=path.join(root,generatorRel);const manifest={schema:'tradercockpit.production-screen-layers/v1',quality:'FULL_RESOLUTION_CAPTURE_SOURCE',generator:generatorRel,generator_sha256:sha(fs.readFileSync(generatorPath)),placement_sha256:sha(fs.readFileSync(path.join(provDir,'screen-placement.json'))),layers};fs.writeFileSync(path.join(provDir,'production-screen-layers.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify(manifest,null,2));
