import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
import {serve,publicFiles} from './reference-preview-server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),docs=path.join(root,'docs');
const pp=process.env.TC_PUPPETEER_MODULE,puppeteer=(await import(pp?pathToFileURL(path.resolve(pp)).href:'puppeteer')).default;
const output=process.env.TC_REFERENCE_EVIDENCE||path.join(root,'.github/evidence/reference-served');fs.mkdirSync(output,{recursive:true});
const host=await serve(docs),profile=fs.mkdtempSync(path.join(os.tmpdir(),'tc-reference-browser-'));let browser,page;const tests=[];
const before=publicFiles(docs),delay=n=>new Promise(r=>setTimeout(r,n)),external=[];
async function launch(){browser=await puppeteer.launch({executablePath:process.env.TC_CHROME,headless:true,userDataDir:profile});page=await browser.newPage();await page.setViewport({width:1440,height:1000});page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host.base))external.push(r.url());});}
async function go(hash=''){await page.goto(host.base+hash,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.commerce==='verified');await page.waitForFunction(expected=>location.hash===expected&&(expected.startsWith('#/')?!document.querySelector('#journey-main').hidden:!document.querySelector('#main').hidden),{},hash);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function check(name,fn){try{await fn();tests.push({name,pass:true});console.log('PASS '+name);}catch(e){tests.push({name,pass:false,error:String(e)});console.log('FAIL '+name+': '+e.message);}}
try{await launch();
 await check('approved homepage title survives enhanced navigation',async()=>{await go();assert.equal(await page.title(),'TraderCockpit | Backtesting & Strategy Validation Guides');await go('#/learn/monte-carlo');await page.click('.j-breadcrumb a[href="#top"]');await page.waitForFunction(()=>location.hash==='#top');assert.equal(await page.title(),'TraderCockpit | Backtesting & Strategy Validation Guides');});
 await check('native Learning link opens enhanced view with selected navigation',async()=>{await go();await page.click('.desktop-nav [data-journey]');await page.waitForFunction(()=>location.hash==='#/learn' && document.querySelector('.desktop-nav [data-journey]')?.getAttribute('aria-current')==='page' && !document.querySelector('#journey-main')?.hidden && document.body.classList.contains('in-journey'));assert.equal(await page.$eval('.desktop-nav [data-journey]',n=>n.getAttribute('aria-current')),'page');});
 await check('active analytics counts enhanced and static guide navigation once',async()=>{
  const p=await browser.newPage(),events=[],errors=[];
  await p.setViewport({width:1440,height:1000});
  await p.exposeFunction('recordGuideEvent',(name,options)=>events.push({name,...options}));
  await p.evaluateOnNewDocument(()=>{globalThis.plausible=(name,options)=>globalThis.recordGuideEvent(name,options);});
  await p.setRequestInterception(true);
  p.on('request',request=>{
   if(request.url().endsWith('/prelaunch-config.v1.json'))return request.respond({status:200,contentType:'application/json',body:JSON.stringify({schema:'prelaunch-config/v1',analytics:{provider:'plausible',status:'active',domain:'tradercockpit.app',scriptSrc:'https://plausible.io/js/script.js'}})});
   if(request.url().startsWith('https://plausible.io/'))return request.respond({status:200,contentType:'text/javascript',body:''});
   request.continue();
  });
  p.on('pageerror',error=>errors.push(String(error)));
  const settle=()=>p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  try{
   await p.goto(host.base,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.prelaunch==='configured');
   await p.click('.desktop-nav [data-journey]');await p.waitForFunction(()=>location.hash==='#/learn');await settle();
   await p.click('a[href="#/learn/monte-carlo"]');await p.waitForFunction(()=>location.hash==='#/learn/monte-carlo');await settle();
   assert.deepEqual(events,[{name:'Guide Click',props:{destination:'/#/learn'}},{name:'Guide Click',props:{destination:'/#/learn/monte-carlo'}}]);
   await p.click('[data-scroll-to="mc-assumptions"]');await settle();
   await p.evaluate(()=>dispatchEvent(new HashChangeEvent('hashchange')));await settle();
   await p.evaluate(()=>{location.hash='#/learn/monte-carlo?example=1';});await settle();
   assert.equal(events.length,2,'section focus, redraw and a query-only route change are not another guide');
   await p.click('.j-breadcrumb a[href="#top"]');await p.waitForFunction(()=>location.hash==='#top');await settle();
   assert.equal(events.length,2,'homepage section navigation is not a guide');
   await p.click('.desktop-nav [data-journey]');await p.waitForFunction(()=>location.hash==='#/learn');await settle();
   await p.click('.desktop-nav [data-journey]');await settle();
   assert.equal(events.length,3,'re-clicking the current Learning view does not count twice');
   await p.click('a[href="#/learn/checklist"]');await p.waitForFunction(()=>location.hash==='#/learn/checklist');await settle();
   assert.deepEqual(events.at(-1),{name:'Guide Click',props:{destination:'/#/learn/checklist'}});
   await p.click('.j-source');await p.waitForFunction(()=>location.pathname.endsWith('/strategy-claim-audit-checklist.html'));await settle();
   assert.equal(events.length,5,'a static guide link still emits exactly one event');
   assert.deepEqual(events.at(-1),{name:'Guide Click',props:{destination:'/strategy-claim-audit-checklist.html'}});
   assert.deepEqual(errors,[]);
  }finally{await p.close();}
 });
 await check('leaving a journey restores and focuses the requested homepage section',async()=>{await go('#/learn');await page.click('.desktop-nav a[href="#pricing"]');await page.waitForFunction(()=>location.hash==='#pricing'&&!document.querySelector('#main')?.hidden&&document.querySelector('#journey-main')?.hidden);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const position=await page.$eval('#pricing',n=>({top:n.getBoundingClientRect().top,height:n.getBoundingClientRect().height,viewport:innerHeight,scrollY,focused:n===document.activeElement}));assert.ok(position.scrollY>0,'pricing navigation should leave the homepage scrolled');assert.ok(position.top>=-2&&position.top<Math.min(250,position.viewport*.25),'pricing section should be brought into the upper viewport after journey exit, got '+position.top);assert.ok(position.top+position.height>0,'pricing section should remain visible after journey exit');assert.equal(position.focused,true,'pricing section should receive keyboard focus after journey exit');await go('#/access?plan=Quant');await page.click('.j-access-explanation a[href="#public-status"]');await page.waitForFunction(()=>location.hash==='#public-status'&&document.querySelector('#public-status')===document.activeElement);await go('#/learn/monte-carlo');await page.click('[data-scroll-to="mc-assumptions"]');await page.waitForFunction(()=>document.activeElement?.id==='mc-assumptions');assert.equal(await page.$eval('#mc-assumptions',n=>n.getAttribute('tabindex')),'-1');});
 await check('malformed homepage fragment cannot break journey exit rendering',async()=>{await go('#/learn');const errors=[];const onError=e=>errors.push(String(e));page.on('pageerror',onError);try{await page.evaluate(()=>{history.pushState(null,'','#%E0%A4%A');dispatchEvent(new HashChangeEvent('hashchange'));});await page.waitForFunction(()=>location.hash==='#%E0%A4%A'&&!document.querySelector('#main')?.hidden&&document.querySelector('#journey-main')?.hidden);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.deepEqual(errors,[]);}finally{page.off('pageerror',onError);}});
 await check('journey evidence links resolve on the current public site',async()=>{for(const [hash,suffix] of [['#/learn/monte-carlo','learn/concepts/monte-carlo.html'],['#/learn/checklist','strategy-claim-audit-checklist.html'],['#/access?plan=Core','commerce-public.v1.json']]){await go(hash);const link=await page.$eval('.j-source',n=>({href:n.href,target:n.target}));assert.equal(link.href,host.base+suffix);assert.equal(link.target,'');}});
 await check('plan selection comes from live local commerce',async()=>{for(const [name,price]of [['Core','$19.99'],['Trader','$49.99'],['Quant','$99.99'],['ApolloPro','$150']]){await go('#/access?plan='+name);assert.equal(await page.$eval('[data-selected-plan]',n=>n.textContent),name);assert.equal(await page.$eval('[data-selected-price]',n=>n.textContent),price);assert.equal(await page.$eval('[data-checkout]',n=>n.disabled),true);}});
 await check('original Charts capture is local, full resolution, and labelled synthetic',async()=>{await go();await page.click('[data-capture="charts"]');await page.waitForSelector('#detail-dialog[open]');await page.waitForFunction(()=>document.querySelector('.capture-media')?.complete);assert.equal(await page.$eval('.capture-media',n=>n.naturalWidth),1220);assert.match(await page.$eval('#dialog-body',n=>n.textContent),/synthetic/);await page.click('[data-capture-scale="native"]');assert.equal(await page.$eval('.capture-evidence',n=>n.classList.contains('native-scale')),true);const reach=await page.$eval('.capture-evidence',frame=>{const image=frame.querySelector('.capture-media');frame.scrollLeft=0;const f0=frame.getBoundingClientRect(),i0=image.getBoundingClientRect(),start=i0.left-f0.left,align=getComputedStyle(frame).alignItems;frame.scrollLeft=frame.scrollWidth;const f1=frame.getBoundingClientRect(),i1=image.getBoundingClientRect(),end=f1.right-i1.right;return{align,start,end,scrollWidth:frame.scrollWidth,clientWidth:frame.clientWidth};});assert.equal(reach.align,'flex-start');assert.ok(reach.scrollWidth>reach.clientWidth);assert.ok(reach.start>=0&&reach.start<24,'native capture left edge unreachable');assert.ok(reach.end>=0&&reach.end<24,'native capture right edge unreachable');await page.click('[data-capture-choice="models"]');await page.waitForFunction(()=>document.querySelector('.capture-media')?.naturalWidth===1440);await page.keyboard.press('Escape');});
 await check('notes save survives full served-site reload',async()=>{await go('#/learn/checklist');await page.type('#research-question','Served-site persistence question');await page.type('#research-notes','Synthetic QA note; not a trading instruction.');await page.click('[data-check="inputs"]');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question','Input must be entered before testing persistence');await page.click('[data-save-notes]');await page.waitForFunction(()=>document.querySelector('[data-note-status]').textContent.startsWith('Saved on this device'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tc-proof-notes-v1')).question),'Served-site persistence question','Stored JSON must contain the entered question');await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#research-question');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question');assert.equal(await page.$eval('[data-check="inputs"]',n=>n.checked),true);});
 await check('notes survive complete browser restart',async()=>{await browser.close();browser=null;await launch();await go('#/learn/checklist');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question');});
 await check('reset cancel preserves and confirm clears stored notes',async()=>{await page.click('[data-reset-notes]');await page.click('[data-cancel-reset]');assert.match(await page.$eval('#research-question',n=>n.value),/persistence/);await page.click('[data-reset-notes]');await page.click('[data-confirm-reset]');assert.equal(await page.$eval('#research-question',n=>n.value),'');assert.equal(await page.evaluate(()=>localStorage.getItem('tc-proof-notes-v1')),null);});
 await check('corrupt storage is visible and not silently overwritten',async()=>{await page.evaluate(()=>localStorage.setItem('tc-proof-notes-v1','corrupt-test-record'));await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-note-status]');assert.match(await page.$eval('[data-note-status]',n=>n.textContent),/could not be read/);assert.equal(await page.evaluate(()=>localStorage.getItem('tc-proof-notes-v1')),'corrupt-test-record');await page.evaluate(()=>localStorage.removeItem('tc-proof-notes-v1'));});
 await check('invalid imported file leaves the current notes unchanged',async()=>{await go('#/learn/checklist');await page.type('#research-question','Keep this local text');const bad=path.join(profile,'invalid-notes.json');fs.writeFileSync(bad,'{"schema":"wrong"}');await (await page.$('[data-import-notes]')).uploadFile(bad);await page.waitForFunction(()=>document.querySelector('[data-note-status]')?.textContent.includes('not a supported'));assert.equal(await page.$eval('#research-question',n=>n.value),'Keep this local text');});
 await check('mobile local search opens, closes, and returns focus',async()=>{await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await go();const targets=await page.evaluate(()=>Object.fromEntries([['brand','.site-header .brand'],['menu','.menu-toggle'],['footer provenance','footer [data-provenance]']].map(([name,selector])=>{const r=document.querySelector(selector).getBoundingClientRect();return[name,{width:r.width,height:r.height}]})));for(const [name,target] of Object.entries(targets))assert.ok(target.width>=44&&target.height>=44,`mobile ${name} target must be at least 44px in both dimensions, got ${target.width}x${target.height}`);await page.click('.menu-toggle');await page.click('.mobile-search');await page.waitForSelector('#search-dialog[open]');await page.type('#search-input','Monte Carlo');assert.match(await page.$eval('#search-results',n=>n.textContent),/Monte Carlo/);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement===document.querySelector('.menu-toggle'),{timeout:3000});assert.equal(await page.$eval('.menu-toggle',n=>n===document.activeElement),true);await page.setViewport({width:1024,height:900,isMobile:false,hasTouch:true});await go();assert.equal(await page.evaluate(()=>matchMedia('(pointer: coarse)').matches),true,'1024px touch viewport must exercise the coarse-pointer contract');const selectors=['.site-header .brand','.desktop-nav a','.site-header [data-search]','.site-header .header-cta','.hero .actions .button','.scene-caption button','.motion-toggle','.platform-copy .button','.price-grid .button','footer [data-provenance]','footer [data-access]','.reference-status summary','.reference-footer-links a'];const wideTargets=await page.evaluate(selectors=>selectors.flatMap(selector=>[...document.querySelectorAll(selector)].filter(node=>{const s=getComputedStyle(node),r=node.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;}).map((node,index)=>{const r=node.getBoundingClientRect();return{name:selector+'['+index+']',width:r.width,height:r.height};})),selectors);assert.ok(wideTargets.length>10,'expected wide coarse-pointer controls');for(const target of wideTargets)assert.ok(target.width>=44&&target.height>=44,`${target.name} must be at least 44px in both dimensions on coarse pointers, got ${target.width}x${target.height}`);});
 await check('reduced motion keeps both scene layers aligned and static',async()=>{await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await go();await page.mouse.move(200,320);assert.equal(await page.$eval('[data-motion-toggle]',n=>n.disabled),true);const transforms=await page.$$eval('.scene-stack',a=>a.map(n=>getComputedStyle(n).transform));assert.ok(transforms.every(v=>v==='none'));await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);});
 await check('development status clears scene controls at intermediate widths and on touch',async()=>{await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);for(const hasTouch of [false,true])for(const width of [1440,1280,1200,1100,1051,1050,1024,901,900,390]){await page.setViewport({width,height:1000,isMobile:false,hasTouch});await go();const result=await page.evaluate(()=>{const note=document.querySelector('.hero-note').getBoundingClientRect(),control=document.querySelector('.hero .motion-toggle').getBoundingClientRect(),hero=document.querySelector('.hero').getBoundingClientRect();return {overlap:note.left<control.right&&note.right>control.left&&note.top<control.bottom&&note.bottom>control.top,fits:note.bottom<=hero.bottom};});assert.equal(result.overlap,false,width+'px '+(hasTouch?'touch':'mouse')+': scene control covers product status');assert.equal(result.fits,true,width+'px: product status overflows hero');}await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);});
 await check('ordinary browsing made no eager external request',async()=>assert.deepEqual(external,[]));
 await check('no-JavaScript homepage keeps documentation links and closed signup',async()=>{const p=await browser.newPage();await p.setJavaScriptEnabled(false);await p.goto(host.base,{waitUntil:'domcontentloaded'});assert.equal(await p.$$eval('form,input[type=email]',n=>n.length),0);assert.equal(await p.$eval('#product-cta',n=>n.hidden),false);assert.equal(await p.$eval('.hero .actions a',n=>n.getAttribute('href')),'learn/');assert.equal(await p.$eval('.desktop-nav [data-journey]',n=>n.getAttribute('href')),'learn/');await p.click('.reference-footer-links a[href="docs/"]');assert.ok(p.url().endsWith('/docs/'));await p.close();});
 await check('pricing plan links progressively enhance to selected plan journey',async()=>{await page.setViewport({width:1440,height:1000});await page.goto(host.base+'pricing/',{waitUntil:'domcontentloaded'});const href=await page.$eval('[data-access-plan="Quant"]',n=>n.getAttribute('href'));assert.equal(href,'../#public-status');await page.click('[data-access-plan="Quant"]');await page.waitForFunction(()=>location.pathname==='/'&&location.hash==='#/access?plan=Quant'&&!document.querySelector('#journey-main')?.hidden);assert.equal(await page.$eval('[data-selected-plan]',n=>n.textContent),'Quant');});
 await check('no-JavaScript public pricing lists all four monthly plans',async()=>{const p=await browser.newPage();await p.setJavaScriptEnabled(false);await p.goto(host.base+'pricing/',{waitUntil:'domcontentloaded'});const text=await p.$eval('main',n=>n.textContent);for(const name of ['Core','Trader','Quant','ApolloPro','$19.99','$49.99','$99.99','$150'])assert.ok(text.includes(name),'Missing published pricing: '+name);const links=await p.$$eval('[data-access-plan]',a=>a.map(n=>n.getAttribute('href')));assert.deepEqual(links,['../#public-status','../#public-status','../#public-status','../#public-status']);await p.close();});
 await check('unknown real route returns 404 and recovery page',async()=>{const response=await fetch(host.base+'not-an-existing-page');assert.equal(response.status,404);assert.match(await response.text(),/404|not found/i);});
 const after=publicFiles(docs);assert.deepEqual(after,before,'Public files changed during interaction tests');
 const result={schema:'tradercockpit.served-interactions/v1',scope:'FULL_INTEGRATED_PUBLISHING_TREE_NAVIGATED_OVER_LOOPBACK_HTTP',browser:await browser.version(),capturedAt:new Date().toISOString(),publicDigest:crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),tests,passed:tests.filter(t=>t.pass).length,failed:tests.filter(t=>!t.pass).length,visualApproval:false};
 fs.writeFileSync(path.join(output,'interactions.json'),JSON.stringify(result,null,2)+'\n');if(result.failed)process.exitCode=1;
}finally{if(browser)await browser.close();await host.close();fs.rmSync(profile,{recursive:true,force:true});}
