/* Integration bridge HTTP fixture; explicitly NOT full website acceptance. */
import fs from 'node:fs'; import path from 'node:path'; import http from 'node:http'; import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const pp=process.env.TC_PUPPETEER_MODULE;
const puppeteer=(await import(pp?pathToFileURL(path.resolve(pp)).href:'puppeteer')).default;
const browserPath=process.env.TC_CHROME;
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const commerce={schema:'public-commerce/v1',status:'prelaunch',plan:{currency:'USD'},tiers:[['Core',1999],['Trader',4999],['Quant',9999],['ApolloPro',15000]].map(([name,unitAmount])=>({name,unitAmount,interval:'month'})),checkout:{enabled:false,url:null}};
const html='<!doctype html><html><head><meta charset="utf-8"><link rel="icon" href="data:,"></head><body><h1>Bridge fixture</h1><p class="hero-note">Access on waitlist</p><a id="learning-link" href="learn/" data-journey="#/learn">Learning</a><div class="price-grid">'+Array.from({length:4},()=>'<article><p class="price"><strong>Checking</strong></p></article>').join('')+'</div>'+read('.github/reference-site/access-panel.html')+'<script type="module" src="assets/reference-site/integration.mjs"></script></body></html>';
let scenario='normal';const checks=[];
const server=http.createServer((req,res)=>{let type='text/javascript',body,status=200;const u=new URL(req.url,'http://127.0.0.1');switch(u.pathname){case '/tradercockpit/':type='text/html';body=html;break;case '/tradercockpit/assets/reference-site/integration.mjs':body=read('docs/assets/reference-site/integration.mjs');break;case '/tradercockpit/product-manifest.mjs':case '/tradercockpit/prelaunch-config.mjs':body=read('docs/'+u.pathname.split('/').pop());break;case '/tradercockpit/product-manifest.v1.json':type='application/json';body=read('docs/product-manifest.v1.json');if(scenario==='failed-product'){status=503;body='{}';}if(scenario==='unavailable'){const obj=JSON.parse(body);obj.status='unavailable';body=JSON.stringify(obj);}break;case '/tradercockpit/prelaunch-config.v1.json':type='application/json';body=read('docs/prelaunch-config.v1.json');break;case '/tradercockpit/commerce-public.v1.json':type='application/json';body=JSON.stringify(scenario==='bad-commerce'?{...commerce,checkout:{enabled:true,url:null}}:commerce);break;default:status=404;body='not found';}res.writeHead(status,{'Content-Type':type+'; charset=utf-8','Cache-Control':'no-store'});res.end(body);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try{browser=await puppeteer.launch({executablePath:browserPath,headless:true});const base='http://127.0.0.1:'+server.address().port+'/tradercockpit/';
for(const mode of ['normal','bad-commerce','failed-product','unavailable']){scenario=mode;const page=await browser.newPage(),external=[],errors=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))external.push(r.url());});page.on('pageerror',e=>errors.push(String(e)));const probe=await fetch(base); assert.equal(probe.status,200); await probe.text(); try{await page.goto(base,{waitUntil:'domcontentloaded',timeout:15000}); await page.waitForFunction(()=>!!document.documentElement.dataset.commerce && document.querySelector('#product-state')?.textContent !== 'Checking availability…' && (document.documentElement.dataset.prelaunch==='waitlist-active'||document.querySelector('#product-state')?.textContent==='Status unavailable'),{timeout:10000});}catch(error){console.error(JSON.stringify({mode,errors,external,url:page.url(),content:(await page.content()).slice(0,300)}));throw error;}
const state=await page.evaluate(()=>({prices:[...document.querySelectorAll('.price strong')].map(n=>n.textContent),commerce:document.documentElement.dataset.commerce,hidden:document.querySelector('#waitlist-form').hidden,action:document.querySelector('#waitlist-form').action,cta:document.querySelector('#product-cta').href,ctaHidden:document.querySelector('#product-cta').hidden,summary:document.querySelector('#product-summary').textContent,note:document.querySelector('.hero-note').textContent}));
assert.deepEqual(external,[],'No external requests before form submission');assert.deepEqual(errors,[],'No page exceptions');
if(mode==='normal'){assert.deepEqual(state.prices,['$19.99','$49.99','$99.99','$150']);assert.equal(state.hidden,false);assert.equal(state.action,'https://app.kit.com/forms/9787408/subscriptions');assert.equal(state.cta,base+'strategy-claim-audit-checklist.html');await page.click('#learning-link');assert.ok(page.url().endsWith('#/learn'));checks.push('valid_commerce','same_origin_product_cta','native_link_upgrade','waitlist_configured_without_submission');}
if(mode==='bad-commerce'){assert.equal(state.commerce,'unavailable');assert.deepEqual(state.prices,Array(4).fill('Unavailable'));checks.push('invalid_commerce_rejected');}
if(mode==='failed-product'){assert.equal(state.hidden,true);assert.equal(state.ctaHidden,true);assert.match(state.note,/could not be verified/);checks.push('failed_product_hides_signup_and_clears_stale_label');}
if(mode==='unavailable'){assert.match(state.summary,/currently unavailable/);checks.push('unavailable_product_copy_truthful');}
await page.close();}
console.log(JSON.stringify({scope:'REAL_INTEGRATION_MODULE_AND_EXISTING_PRODUCT_PRELAUNCH_MODULES_IN_MINIMAL_HTTP_FIXTURE_NOT_FULL_SITE',browser:await browser.version(),moduleSha256:crypto.createHash('sha256').update(read('docs/assets/reference-site/integration.mjs')).digest('hex'),checks,externalRequests:0},null,2));
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
