import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
import {serve,publicFiles} from './reference-preview-server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),docs=path.join(root,'docs');
const puppeteer=(await import(process.env.TC_PUPPETEER_MODULE?pathToFileURL(process.env.TC_PUPPETEER_MODULE).href:'puppeteer')).default;
const out=process.env.TC_REFERENCE_EVIDENCE||path.join(root,'.github/evidence/reference-continuity-served');fs.mkdirSync(out,{recursive:true});
const before=publicFiles(docs),host=await serve(docs),checks=[],external=[];let browser;
try{browser=await puppeteer.launch({executablePath:process.env.TC_CHROME,headless:true});const p=await browser.newPage();p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host.base))external.push(r.url());});
 await p.goto(host.base+'docs/',{waitUntil:'domcontentloaded'});await p.waitForSelector('.site-search-trigger');await p.focus('.site-search-trigger');await p.keyboard.press('Enter');await p.waitForSelector('.site-search-dialog[open]');await p.waitForFunction(()=>document.activeElement?.id==='site-search-input');
 assert.equal(await p.$eval('#site-search-input',n=>n===document.activeElement),true);await p.type('#site-search-input','Monte Carlo');await p.waitForSelector('.site-search-result');assert.ok(await p.$$eval('.site-search-result',n=>n.length)>0);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.site-search-dialog').open);assert.equal(await p.$eval('.site-search-trigger',n=>n===document.activeElement),true);checks.push('wrapped_docs_keyboard_search_and_focus_return');
 await p.goto(host.base+'strategy-claim-audit-checklist.html',{waitUntil:'domcontentloaded'});await p.waitForSelector('[data-reference-added-nav]');assert.notEqual(await p.$eval('[data-reference-added-nav]',n=>getComputedStyle(n).display),'none');
 await p.emulateMediaType('print');assert.equal(await p.$eval('[data-reference-added-nav]',n=>getComputedStyle(n).display),'none');assert.equal(await p.$eval('.print',n=>getComputedStyle(n).display),'none');assert.equal(await p.$eval('.capture-off',n=>getComputedStyle(n).display),'none');assert.match(await p.$eval('h1',n=>n.textContent),/Strategy-Claim/);checks.push('checklist_navigation_visible_on_screen_hidden_in_print');
 assert.deepEqual(external,[]);checks.push('no_eager_external_requests');assert.deepEqual(before,publicFiles(docs));
 const result={schema:'tradercockpit.reference-content-controls/v1',scope:'FULL_SERVED_WEBSITE_NOT_FIXTURE',browser:await browser.version(),publicDigest:crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),checks,failures:0,visualApproval:false};fs.writeFileSync(path.join(out,'content-controls.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}finally{if(browser)await browser.close();await host.close();}
