import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
import {serve,publicFiles} from './reference-preview-server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),docs=path.join(root,'docs');
const pp=process.env.TC_PUPPETEER_MODULE,puppeteer=(await import(pp?pathToFileURL(path.resolve(pp)).href:'puppeteer')).default;
const output=process.env.TC_REFERENCE_EVIDENCE||path.join(root,'.github/evidence/reference-served');fs.mkdirSync(output,{recursive:true});
const host=await serve(docs),profile=fs.mkdtempSync(path.join(os.tmpdir(),'tc-reference-browser-'));let browser,page;const tests=[];
const before=publicFiles(docs),delay=n=>new Promise(r=>setTimeout(r,n)),external=[];
async function launch(){browser=await puppeteer.launch({executablePath:process.env.TC_CHROME,headless:true,userDataDir:profile});page=await browser.newPage();await page.setViewport({width:1440,height:1000});page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host.base))external.push(r.url());});}
async function go(hash=''){await page.goto(host.base+hash,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.commerce==='verified');await page.waitForFunction(expected=>location.hash===expected&&(expected.startsWith('#/')?!document.querySelector('#journey-main').hidden:!document.querySelector('#main').hidden),{},hash);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function check(name,fn){try{await fn();tests.push({name,pass:true});console.log('PASS '+name);}catch(e){tests.push({name,pass:false,error:String(e)});console.log('FAIL '+name+': '+e.message);}}
try{await launch();
 await check('native Learning link opens enhanced view with selected navigation',async()=>{await go();await page.click('.desktop-nav [data-journey]');await page.waitForFunction(()=>location.hash==='#/learn' && document.querySelector('.desktop-nav [data-journey]')?.getAttribute('aria-current')==='page' && !document.querySelector('#journey-main')?.hidden && document.body.classList.contains('in-journey'));assert.equal(await page.$eval('.desktop-nav [data-journey]',n=>n.getAttribute('aria-current')),'page');});
 await check('plan selection comes from live local commerce',async()=>{for(const [name,price]of [['Core','$19.99'],['Trader','$49.99'],['Quant','$99.99'],['ApolloPro','$150']]){await go('#/access?plan='+name);assert.equal(await page.$eval('[data-selected-plan]',n=>n.textContent),name);assert.equal(await page.$eval('[data-selected-price]',n=>n.textContent),price);assert.equal(await page.$eval('[data-checkout]',n=>n.disabled),true);}});
 await check('original Charts capture is local, full resolution, and labelled synthetic',async()=>{await go();await page.click('[data-capture="charts"]');await page.waitForSelector('#detail-dialog[open]');await page.waitForFunction(()=>document.querySelector('.capture-media')?.complete);assert.equal(await page.$eval('.capture-media',n=>n.naturalWidth),1220);assert.match(await page.$eval('#dialog-body',n=>n.textContent),/synthetic/);await page.click('[data-capture-scale="native"]');assert.equal(await page.$eval('.capture-evidence',n=>n.classList.contains('native-scale')),true);await page.click('[data-capture-choice="models"]');await page.waitForFunction(()=>document.querySelector('.capture-media')?.naturalWidth===1440);await page.keyboard.press('Escape');});
 await check('notes save survives full served-site reload',async()=>{await go('#/learn/checklist');await page.type('#research-question','Served-site persistence question');await page.type('#research-notes','Synthetic QA note; not a trading instruction.');await page.click('[data-check="inputs"]');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question','Input must be entered before testing persistence');await page.click('[data-save-notes]');await page.waitForFunction(()=>document.querySelector('[data-note-status]').textContent.startsWith('Saved on this device'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tc-proof-notes-v1')).question),'Served-site persistence question','Stored JSON must contain the entered question');await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#research-question');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question');assert.equal(await page.$eval('[data-check="inputs"]',n=>n.checked),true);});
 await check('notes survive complete browser restart',async()=>{await browser.close();browser=null;await launch();await go('#/learn/checklist');assert.equal(await page.$eval('#research-question',n=>n.value),'Served-site persistence question');});
 await check('reset cancel preserves and confirm clears stored notes',async()=>{await page.click('[data-reset-notes]');await page.click('[data-cancel-reset]');assert.match(await page.$eval('#research-question',n=>n.value),/persistence/);await page.click('[data-reset-notes]');await page.click('[data-confirm-reset]');assert.equal(await page.$eval('#research-question',n=>n.value),'');assert.equal(await page.evaluate(()=>localStorage.getItem('tc-proof-notes-v1')),null);});
 await check('corrupt storage is visible and not silently overwritten',async()=>{await page.evaluate(()=>localStorage.setItem('tc-proof-notes-v1','corrupt-test-record'));await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-note-status]');assert.match(await page.$eval('[data-note-status]',n=>n.textContent),/could not be read/);assert.equal(await page.evaluate(()=>localStorage.getItem('tc-proof-notes-v1')),'corrupt-test-record');await page.evaluate(()=>localStorage.removeItem('tc-proof-notes-v1'));});
 await check('invalid imported file leaves the current notes unchanged',async()=>{await go('#/learn/checklist');await page.type('#research-question','Keep this local text');const bad=path.join(profile,'invalid-notes.json');fs.writeFileSync(bad,'{"schema":"wrong"}');await (await page.$('[data-import-notes]')).uploadFile(bad);await page.waitForFunction(()=>document.querySelector('[data-note-status]')?.textContent.includes('not a supported'));assert.equal(await page.$eval('#research-question',n=>n.value),'Keep this local text');});
 await check('mobile local search opens, closes, and returns focus',async()=>{await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await go();await page.click('.menu-toggle');await page.click('.mobile-search');await page.waitForSelector('#search-dialog[open]');await page.type('#search-input','Monte Carlo');assert.match(await page.$eval('#search-results',n=>n.textContent),/Monte Carlo/);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement===document.querySelector('.menu-toggle'),{timeout:3000});assert.equal(await page.$eval('.menu-toggle',n=>n===document.activeElement),true);});
 await check('reduced motion keeps both scene layers aligned and static',async()=>{await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await go();await page.mouse.move(200,320);assert.equal(await page.$eval('[data-motion-toggle]',n=>n.disabled),true);const transforms=await page.$$eval('.scene-stack',a=>a.map(n=>getComputedStyle(n).transform));assert.ok(transforms.every(v=>v==='none'));await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);});
 await check('ordinary browsing made no eager external request',async()=>assert.deepEqual(external,[]));
 await check('video connects only after explicit consent and stops on close',async()=>{await page.setViewport({width:1440,height:1000});await go();const requests=[];await page.setRequestInterception(true);page.on('request',r=>{if(r.url().startsWith('https://www.youtube-nocookie.com/')){requests.push(r.url());r.abort();}else r.continue();});await page.click('.hero [data-video]');assert.equal(await page.$$eval('iframe',a=>a.length),0);assert.deepEqual(requests,[]);await page.click('#load-video');await page.waitForSelector('iframe');assert.match(await page.$eval('iframe',n=>n.src),/^https:\/\/www\.youtube-nocookie\.com\/embed\//);await delay(150);await page.keyboard.press('Escape');assert.equal(await page.$$eval('iframe',a=>a.length),0);assert.equal(requests.length,1);await page.setRequestInterception(false);});
 await check('no-JavaScript homepage keeps documentation links and closed signup',async()=>{const p=await browser.newPage();await p.setJavaScriptEnabled(false);await p.goto(host.base,{waitUntil:'domcontentloaded'});assert.equal(await p.$eval('#waitlist-form',n=>n.hidden),true);assert.equal(await p.$eval('#product-cta',n=>n.hidden),true);assert.equal(await p.$eval('.desktop-nav [data-journey]',n=>n.getAttribute('href')),'learn/');await p.click('.reference-footer-links a[href="docs/"]');assert.ok(p.url().endsWith('/docs/'));await p.close();});
 await check('no-JavaScript public pricing lists all four monthly plans',async()=>{const p=await browser.newPage();await p.setJavaScriptEnabled(false);await p.goto(host.base+'pricing/',{waitUntil:'domcontentloaded'});const text=await p.$eval('main',n=>n.textContent);for(const name of ['Core','Trader','Quant','ApolloPro','$19.99','$49.99','$99.99','$150'])assert.ok(text.includes(name),'Missing published pricing: '+name);await p.close();});
 await check('unknown real route returns 404 and recovery page',async()=>{const response=await fetch(host.base+'not-an-existing-page');assert.equal(response.status,404);assert.match(await response.text(),/404|not found/i);});
 const after=publicFiles(docs);assert.deepEqual(after,before,'Public files changed during interaction tests');
 const result={schema:'tradercockpit.served-interactions/v1',scope:'FULL_INTEGRATED_PUBLISHING_TREE_NAVIGATED_OVER_LOOPBACK_HTTP',browser:await browser.version(),capturedAt:new Date().toISOString(),publicDigest:crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),tests,passed:tests.filter(t=>t.pass).length,failed:tests.filter(t=>!t.pass).length,visualApproval:false};
 fs.writeFileSync(path.join(output,'interactions.json'),JSON.stringify(result,null,2)+'\n');if(result.failed)process.exitCode=1;
}finally{if(browser)await browser.close();await host.close();fs.rmSync(profile,{recursive:true,force:true});}
