import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),docs=path.join(root,'docs'),prov=path.join(root,'.github/reference-site/provenance/production-screen-layers.json');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
assert.ok(fs.existsSync(prov),'production screen-layer provenance must exist');
const m=JSON.parse(fs.readFileSync(prov,'utf8'));assert.equal(m.schema,'tradercockpit.production-screen-layers/v1');assert.equal(m.quality,'FULL_RESOLUTION_CAPTURE_SOURCE');
const expected={room:{capture:'data',source:'original-data.png',sourceSha:'e5fa50188b251ba679b4881119deb73c1fabdd928a6b3ae8b50c3a18b796c566',output:'room-screen.webp',size:[2048,884],css:[1024,442]},laptop:{capture:'models',source:'original-models.png',sourceSha:'1609ccbb8fb7947190af38b141a01ce52eec4b53fd81031748b9dd3465d52dd2',output:'laptop-screen.webp',size:[2048,628],css:[1024,314]}};
for(const [scene,e] of Object.entries(expected)){const x=m.layers.find(v=>v.scene===scene);assert.ok(x,'missing '+scene);assert.equal(x.capture,e.capture);assert.equal(x.source_asset,'docs/assets/reference-site/'+e.source);assert.equal(sha(path.join(docs,'assets/reference-site',e.source)),e.sourceSha);assert.deepEqual(x.output_dimensions,e.size);assert.deepEqual(x.css_dimensions,e.css);assert.equal(x.output_scale,2);assert.equal(sha(path.join(docs,'assets/reference-site',e.output)),x.output_sha256);assert.equal(x.source_sha256,e.sourceSha);assert.equal(x.generator,'.github/scripts/generate_reference_screen_layers.mjs');}
const placement=Object.fromEntries(JSON.parse(fs.readFileSync(path.join(root,'.github/reference-site/provenance/screen-placement.json'),'utf8')).specs.map(x=>[x.scene,x]));
const pp=process.env.TC_PUPPETEER_MODULE;const puppeteer=(await import(pp?pathToFileURL(path.resolve(pp)).href:'puppeteer')).default;let browser;
try{browser=await puppeteer.launch({executablePath:process.env.TC_CHROME,headless:true});for(const [scene,e] of Object.entries(expected)){const p=await browser.newPage();const file=path.join(docs,'assets/reference-site',e.output).replaceAll('\\','/');await p.goto('file:///'+file);const px=await p.evaluate(async()=>{const img=document.querySelector('img');await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const g=c.getContext('2d');g.drawImage(img,0,0);const d=g.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1,count=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){if(d[(y*c.width+x)*4+3]>8){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++;}}return{w:c.width,h:c.height,minX,minY,maxX,maxY,count};});assert.deepEqual([px.w,px.h],e.size);const layer=m.layers.find(v=>v.scene===scene),corners=placement[scene].corners,scale=layer.output_scale,expectedBounds=[Math.min(...corners.map(x=>x[0]))*scale,Math.min(...corners.map(x=>x[1]))*scale,Math.max(...corners.map(x=>x[0]))*scale,Math.max(...corners.map(x=>x[1]))*scale];for(let i=0;i<4;i++)assert.ok(Math.abs([px.minX,px.minY,px.maxX,px.maxY][i]-expectedBounds[i])<=3,scene+' must preserve full monitor/laptop screen-plane footprint at output scale');await p.close();}}finally{if(browser)await browser.close();}
console.log(JSON.stringify({layers:2,quality:m.quality,status:'PASS'},null,2));