import fs from 'node:fs';import path from 'node:path';import cp from 'node:child_process';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {publicFiles} from './reference-preview-server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),docs=path.join(root,'docs');
const out=path.join(root,'.github/evidence/reference-continuity-served');fs.mkdirSync(out,{recursive:true});
const py=process.env.TC_PYTHON||'python',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=args=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();
const implementation=git(['rev-parse','HEAD']),publicTree=git(['rev-parse','HEAD:docs']);
if(git(['branch','--show-current'])!=='codex/website-reference-integration-20260918')throw new Error('Wrong integration branch');
const initialStatus=git(['status','--porcelain=v1','--untracked-files=all']);
if(initialStatus)throw new Error('Exact-source verification requires a completely clean worktree before execution:\n'+initialStatus);
const archive=process.env.TC_REFERENCE_ARCHIVE;
const archiveSha='0b0ee403e7f21773a1fb1c61520f467c39987a1dce44c7ed69aca8e5599f3a4c';
if(!archive||!fs.existsSync(archive))throw new Error('Exact-source verification requires TC_REFERENCE_ARCHIVE pointing to the approved source ZIP');
if(sha(fs.readFileSync(archive))!==archiveSha)throw new Error('TC_REFERENCE_ARCHIVE does not match the approved source SHA-256');
const before=publicFiles(docs),digest=sha(JSON.stringify(before)),logs={};
function run(name,exe,args,cwd=root){console.log('VERIFY '+name);const r=cp.spawnSync(exe,args,{cwd,encoding:'utf8',env:{...process.env,TC_REFERENCE_EVIDENCE:out},timeout:180000,maxBuffer:16*1024*1024});const log=(r.stdout||'')+(r.stderr||'');logs[name]={exitCode:r.status,output:log};if(r.status!==0){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({implementation,publicTree,logs,error:String(r.error||'')},null,2)+'\n');throw new Error(name+' failed: '+log.slice(-4000));}}
for(const f of ['test_reference_import.py','test_reference_integrity.py','test_reference_contracts.py','test_review_state.py','test_public_journey_sources.py','test_privacy_runtime_contract.py','test_pricing_fallback.py','check_reference_site.py','check_website.py','check_site_hardening.py','check_public_claims.py','check_public_ux.py'])run(f,py,['.github/scripts/'+f]);
const archiveTestLog=logs['test_reference_import.py'].output;
if(!/Ran 10 tests\b/.test(archiveTestLog)||/skipped?\b/i.test(archiveTestLog))throw new Error('Archive/import acceptance must run all 10 tests with zero skips');
run('concepts',py,['.github/scripts/generate_concept_pages.py','--check']);
for(const file of ['docs/assets/site-search.js','docs/assets/reference-site/app.js','docs/assets/reference-site/journeys.js','docs/assets/reference-site/integration.mjs','.github/scripts/generate_reference_screen_layers.mjs','.github/scripts/test_reference_screen_layers.mjs','.github/scripts/package_reference_content_evidence.mjs','.github/scripts/test_reference_evidence_package.mjs'])run('syntax '+file,process.execPath,['--check',file]);
run('screen_layer_regeneration',process.execPath,['.github/scripts/generate_reference_screen_layers.mjs']);
run('screen_layer_source_quality',process.execPath,['.github/scripts/test_reference_screen_layers.mjs']);
run('integration_bridge_failures',process.execPath,['.github/scripts/test_reference_bridge.mjs']);
run('content_browsers',process.execPath,['.github/scripts/test_reference_content.mjs','--all']);
run('package_reading_evidence',process.execPath,['.github/scripts/package_reference_content_evidence.mjs']);
run('reading_evidence_package',process.execPath,['.github/scripts/test_reference_evidence_package.mjs']);
run('all_routes',process.execPath,['.github/scripts/test_reference_served.mjs','--all']);
run('interaction_journeys',process.execPath,['.github/scripts/test_reference_journeys.mjs']);
run('reading_controls',process.execPath,['.github/scripts/test_reference_content_controls.mjs']);
const npm=process.platform==='win32'?'cmd.exe':'npm';const npmArgs=args=>process.platform==='win32'?['/d','/s','/c','npm '+args.join(' ')]:args;
run('production_build',npm,npmArgs(['run','build:check']),path.join(root,'.github/site-build'));run('npm_audit',npm,npmArgs(['audit','--json']),path.join(root,'.github/site-build'));
if(JSON.stringify(before)!==JSON.stringify(publicFiles(docs))||git(['diff','HEAD','--','docs']))throw new Error('Publishing files changed during verification');
const allowedEvidence=['.github/evidence/reference-continuity-served/','.github/evidence/reference-content/'];
const unexpectedStatus=git(['status','--porcelain=v1','--untracked-files=all']).split(/\\r?\\n/).filter(Boolean).filter(line=>{const file=line.slice(3).replaceAll('\\\\','/');return !allowedEvidence.some(prefix=>file.startsWith(prefix));});
if(unexpectedStatus.length)throw new Error('Verification inputs drifted from recorded HEAD during execution:\n'+unexpectedStatus.join('\n'));
run('diff_check','git',['diff','--check']);
const read=name=>JSON.parse(fs.readFileSync(name,'utf8'));
const content=read(path.join(root,'.github/evidence/reference-content/after/receipt.json')),served=read(path.join(out,'receipt.json')),interactions=read(path.join(out,'interactions.json')),controls=read(path.join(out,'content-controls.json'));
for(const receipt of [content,served,interactions,controls])if(receipt.publicDigest!==digest)throw new Error('Receipt is not bound to the same publishing bytes');
if(content.rows.length!==78||content.failures!==0||served.count!==94||served.failures!==0||interactions.tests.length!==18||interactions.tests.some(t=>!t.pass)||controls.failures!==0)throw new Error('Acceptance count or result mismatch');
const m=read(path.join(root,'.github/reference-content-manifest.json'));
if(before['index.html']!==m.home_sha256)throw new Error('Homepage drift');
const audit=JSON.parse(logs.npm_audit.output.slice(logs.npm_audit.output.indexOf('{')));if(audit.metadata.vulnerabilities.total!==0)throw new Error('Dependency findings remain');
const layerManifest=read(path.join(root,'.github/reference-site/provenance/production-screen-layers.json'));
const readiness=read(path.join(root,'.github/website-reference-readiness.json'));
const ownerVisualApproval=String(readiness.gates?.owner_visual_acceptance_of_integrated_result||'').startsWith('complete');
const checkpoint={schema:'tradercockpit.reference-continuity-checkpoint/v1',implementationCommit:implementation,publicTree,publicDigest:digest,browser:served.browser,scope:served.scope,referenceVisualBaselineCommit:'aceeef931a54d230133e53296fb810d94e0dd0a7',homeSha256:before['index.html'],screenLayerQuality:layerManifest.quality,screenLayers:layerManifest.layers.map(x=>({scene:x.scene,capture:x.capture,sourceSha256:x.source_sha256,outputSha256:x.output_sha256,alphaBounds:x.alpha_bounds})),readingPages:39,readingRenders:content.rows.length,readingFailures:content.failures,servedRoutes:served.count,servedFailures:served.failures,interactionTests:interactions.tests.length,interactionFailures:0,additionalReadingControls:controls.checks,archiveTests:10,integrityTests:17,contractTests:4,reviewStateTests:2,publicJourneySourceTests:2,privacyRuntimeTests:2,pricingFallbackTests:2,evidencePackageTests:1,integrationBridgeChecks:7,npmVulnerabilities:audit.metadata.vulnerabilities.total,logs,automatedVisualApproval:false,ownerVisualApproval,reviewReady:ownerVisualApproval,reviewStateSource:'github_pr_external',remaining:ownerVisualApproval?['Independent Codex review before any separately authorized deployment']:['Owner acceptance of integrated homepage and reading surfaces','Independent Codex review before any separately authorized deployment'],noMergeOrDeploymentRequested:true};
fs.writeFileSync(path.join(out,'checkpoint.json'),JSON.stringify(checkpoint,null,2)+'\n');
fs.rmSync(path.join(root,'.github/evidence/reference-content'),{recursive:true,force:true});
console.log(JSON.stringify({...checkpoint,logs:Object.fromEntries(Object.keys(logs).map(k=>[k,'PASS']))},null,2));
